using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Spirits : MonoBehaviour
{
    public enum SpiritType  //英灵种类
    {
        Float = 0,       //漂浮
        Dash = 1,      //冲刺
        Kebab = 2,      //烤串
        Invisible = 3,  //隐身
    }

    public SpiritType currentSpirit;


    public void SummonSpirit(SpiritType st)
    {
        switch (st)
        {
            case SpiritType.Float:
                break;
            case SpiritType.Dash:
                break;
            case SpiritType.Invisible:
                break;
            case SpiritType.Kebab:
                break;
        }
    }

    
    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.P))
        {
            currentSpirit = SpiritType.Float;
            SummonSpirit(currentSpirit);
        }
        if (Input.GetKeyDown(KeyCode.O))
        {
            currentSpirit = SpiritType.Invisible;
            SummonSpirit(currentSpirit);
        }
    }
}
